name: test perms
on:
  workflow_dispatch:
jobs:
  test:
    environment: spincast-production
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - run: echo ok
